spring:
  datasource:
    driver-class-Name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: "postgres"
    password: "1234"
  liquibase:
    change-log: db/changelog/db.changelog-master.yml

telegram:
  enable: ${TELEGRAM_ENABLE:true}
  bot:
    username: ${BOT_USERNAME}
    token: ${TOKEN}
    bot-owner-id: ${BOT_OWNER_ID}